server:
  port: 16802
# 若要访问端点信息，需要用户名和密码
spring:
  security:
    user:
      name: hnnwb
      password: hnnwb
#端点信息接口使用的端口，和主系统分离
management:
  server:
    port: 16803
    base-path: /sys
#端点健康情况，默认值“never”,设置为“always”可以显示硬盘使用情况和线程情况
  endpoint:
    health:
      show-details: always
#设置端点暴露的哪些内容，默认【“health”，“info”】,设置“*”代表暴露所有可访问的端点
  endpoints:
    web:
      exposure:
        include: '*'